import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../src/components/Header'
import Card from '../src/components/Card'
import Card2 from '../src/components/Card2'
import Card3 from '../src/components/Card3'
import Card4 from '../src/components/Card4'
import Grid from '@material-ui/core/Grid'
import { makeStyles } from '@material-ui/core/styles'
import { Box, Container, Typography } from '@material-ui/core'
import Divider from '@mui/material/Divider';
import Image from 'next/image'
const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
    justifyContent: 'center',
    marginTop: '100px'
  },
  paper: {
    height: 140,
    width: 100,
  },
  control: {
    padding: theme.spacing(2),
  },
  title: {

    color: '#fff',
    display: 'flex',
    justifyContent: 'center',
    marginTop: '16rem',
  },
  titleS: {
    padding: '10px',
  },
  divider: {
    marginBottom: '25px',
  },
  footer: {
    width: '100%',
    marginTop: '3rem'
  },
  introduction: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  introductionText: {
    padding: '15px'
  },
  img: {
    zIndex: -1,
    display: 'flex',
  }
}));

export default function Home() {
  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>Pousada Sol do Rosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/logo.jpg" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <Header />

      <main className={styles.main}>
        <Container>
          <Image
            alt="teste"
            src="https://i.imgur.com/2LWogXg.jpg"
            fill
            sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                33vw"
            className={classes.img} />
          <Box className={classes.title}>
          </Box>
        </Container>
        <Divider sx={{
          marginTop: '40%'
        }} ><Typography variant="body1" component="div" >
            Sobre
          </Typography></Divider>

        <Grid container className={classes.root} spacing={2}>
          <Grid item md={6}>
            <Image
              src="https://i.imgur.com/2LWogXg.jpg"
              alt="Picture of the author"
              width={800}
              height={600}
            />
          </Grid>
          <Grid item md={6} className={classes.introduction}>
            <Typography component="p" align='justify' className={classes.introductionText} >
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores aspernatur dolorum enim tempore accusantium nobis
              architecto inventore quisquam perspiciatis quia dolores voluptates doloremque odit, aliquid repellat! Odio eaque accusamus ad?
            </Typography>
          </Grid>
        </Grid>
        <Divider sx={{
          marginTop: '4rem'
        }} >
          <Typography variant="body1" component="div" >
            Quartos
          </Typography>
        </Divider>
        <Grid container className={classes.root} spacing={2}>
          <Grid item md={4}>
            <Card title={"Quarto 1 - 2"} />
          </Grid>

          <Grid item md={4}>
            <Card2 title={"Quarto 3 - 4"} />
          </Grid>

          <Grid item md={4}>
            <Card3 title={"Quarto 5 - 6 - 7"} />
          </Grid>

          <Grid item md={4}>
            <Card4 title={"Chalé"} />
          </Grid>
        </Grid>

      </main>

      <footer className={classes.footer}>
        <Divider sx={{
          marginTop: '3rem',
          marginBottom: '1rem'
        }} ></Divider>
        <Box component="footer" sx={{ bgcolor: '#7fa7c9', py: 6 }}>
          <Container maxWidth="lg">
            <Typography variant="body1" align="center">
              {'Pousada Sol do Rosa  © '}
              {new Date().getFullYear()}
              {'.'}
            </Typography>
          </Container>
        </Box>
      </footer>
    </div>
  )
}
